combat_attribute = 'data/Palworld_Data--Palu combat attribute table.csv'
refresh_level = 'data/Palworld_Data--Palu refresh level.csv'
ordinary_BOSS_attributes = 'data/Palworld_Data-comparison of ordinary BOSS attributes.csv'
hide_pallu_attributes = 'data/Palworld_Data-hide pallu attributes.csv'
Palu_Job_Skills_Table = 'data/Palworld_Data-Palu Job Skills Table.csv'
TowercBOSScattributec_comparison = 'data/Palworld_Data-Tower BOSS attribute comparison.csv'